---
title: "Airline Delays - 2015 Review"
date: "Monday, May 04, 2015"
output: html_document
---
```{r echo=FALSE, warning=FALSE}
library(ggplot2)
library(reshape2)

setwd("C:/Users/Gary/Desktop/Data Science Specialzation/Contract Projects/Airline delays")
filenm = "airline_delay_causes.csv"
flydata <- read.csv(filenm,header=TRUE)


```
## Synopsis.
#### In February of 2015, airline carriers at various airports were logged by their different types of delays: late arrivals, weather, security, cancellations, diverted flights, etc.  Our data shows the number of events as well as the total time lost due to the different types of delays.  

```{r echo=FALSE, cache=TRUE}

## step 1:  make the data tidy.  melt the df and recast matching one observation per row.
flights <- melt(flydata, id=c("year","month","carrier","carrier_name","airport","airport_name"))

## develop the percentage of flights variable
pct <- NULL
x <- nrow(flights)
for (i in 1:x) {
      airline <- flights$carrier[i]
      airports <- flights$airport[i]
      arriving <- flights[flights$carrier==airline & 
                  flights$airport==airports & 
                  flights$variable=="arr_flights",8]
      pct[i] <- flights$value[i]/arriving
      }
flights <- cbind(flights,pct)
flights$pct <- round(flights$pct*100,digits=2)


```
### Exploratory Data Analysis.

```{r echo = FALSE, warning=FALSE, message=FALSE}

```
